# Generated by Django 3.2.7 on 2023-08-16 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Anonymous', max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('CheckIn', models.DateTimeField(default=datetime.datetime(2023, 8, 16, 21, 36, 1, 287863))),
                ('CheckOut', models.DateTimeField()),
                ('SpecialRequest', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Anonymous', max_length=200)),
                ('Email', models.CharField(max_length=50)),
                ('Subject', models.CharField(max_length=500)),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Price', models.CharField(max_length=30)),
                ('Description', models.TextField()),
                ('Star', models.IntegerField()),
                ('Image', models.ImageField(upload_to='static/images')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=300)),
            ],
        ),
    ]
