# Generated by Django 3.2.7 on 2023-08-16 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AwevilleApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rooms',
            new_name='Room',
        ),
        migrations.AlterField(
            model_name='booking',
            name='CheckIn',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 21, 49, 42, 835899)),
        ),
    ]
