# Generated by Django 3.2.7 on 2023-08-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AwevilleApp', '0002_auto_20230816_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='CheckIn',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='CheckOut',
            field=models.CharField(max_length=50),
        ),
    ]
