# Generated by Django 3.2.7 on 2023-08-21 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AwevilleApp', '0004_auto_20230821_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='CheckIn',
            field=models.CharField(default=datetime.datetime(2023, 8, 21, 12, 8, 33, 316889), editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='CheckOut',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
