# Generated by Django 3.2.7 on 2023-08-21 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AwevilleApp', '0005_auto_20230821_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='DateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 21, 12, 10, 17, 507899), editable=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='CheckIn',
            field=models.CharField(default=datetime.datetime(2023, 8, 21, 12, 10, 17, 506899), max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='CheckOut',
            field=models.CharField(max_length=50),
        ),
    ]
