# Generated by Django 3.2.7 on 2023-08-24 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AwevilleApp', '0006_auto_20230821_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='DatePub',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 24, 8, 16, 32, 261400), editable=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='CheckIn',
            field=models.CharField(default=datetime.datetime(2023, 8, 24, 8, 16, 32, 260401), max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='DateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 24, 8, 16, 32, 260401), editable=False),
        ),
    ]
