# Generated by Django 3.2.7 on 2023-08-24 12:51

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('AwevilleApp', '0013_auto_20230824_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='CheckIn',
            field=models.CharField(default=datetime.datetime(2023, 8, 24, 13, 51, 46, 742476), max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='DateSubmitted',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 24, 13, 51, 46, 742476), editable=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='uniqueID',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='DatePub',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 24, 13, 51, 46, 743475), editable=False),
        ),
    ]
